### ISSUE TITLE
autoForward selected repsonse

### ISSUE THREAD

**Issue by diana1357** [AskiaADX/StatementList#4]
Hi

When autoForward is set to yes, the selected response colour cannot be seen. You can see the hover colour, but it moves straight to the next statement, without showing the selected response colour.
In the previous version of the adc we could see the selected response colour briefly before moving on.

Thanks
diana

**Comment by Djedj** [comment]
Hi @diana1357 

Should be fixed in the version 2.0.6

Best Regards
