### ISSUE TITLE
hide next button

### ISSUE THREAD

**Issue by diana1357** [AskiaADX/StatementList#5]
When I select the following, the statement is not visible:

Autoforward: no
Hide next button:  Always or Until itesm displayed or Until all items answered
Disable return on submit: **Yes**
Top buttons: hide both
Bottom buttons: show next

When I change disable return on submit to "No" it works. 

![statement-list](https://user-images.githubusercontent.com/20987595/31609129-cfc04de4-b26a-11e7-99ec-ae4e6f72b3ef.jpg)

**Comment by Djedj** [comment]
Hi @diana1357,

It should be fixed in the v2.0.5

Best Regards
