### ISSUE TITLE
next button error

### ISSUE THREAD

**Issue by diana1357** [AskiaADX/StatementList#6]
Hi

With autoforward=on, show next button, buttons hidden,  if I click on next without answering, the question goes to a different statement.
e.g:  I clicked next at "Item 5"  without selecting an answer, and now I'm shown "Item 1"
![statementlist](https://user-images.githubusercontent.com/20987595/31673588-8859eb5c-b357-11e7-839b-bf7afe1367bc.PNG)

As a consequence, when reaching the last statment in the loop it is not possible to proceed. 

For now I've hidden "Next" but it would be good to have a solution for this.

Thanks,
Diana

**Comment by Djedj** [comment]
Hi @diana1357 

Which version of the adc do you use ?

Best Regards

**Comment by diana1357** [comment]
Hi @Djedj 

It is 2.0.7. I'm attaching qex with both statement lis & responsive table.
[Example_adcs.zip](https://github.com/AskiaADX/StatementList/files/1391693/Example_adcs.zip)

Thanks
Diana

**Comment by Djedj** [comment]
Hi @diana1357 ,

Should be fixed in v2.0.8 of the adc.

Can you tell us if it makes the trick ?

Best Regards

**Comment by diana1357** [comment]
Thanks once again, all good!
